sudo: required
dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build
  - cargo test
  - cargo test --release --no-run
  - ./target/release/examples/bench
  - cd bogo && ./runme
