language: rust
os:
  - linux
  - osx
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8i
  allow_failures:
    - os: osx
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build
  - cargo test
  - cargo test --release --no-run
  - ./target/release/examples/bench
  - cd bogo && ./runme
