language: rust
os:
  - linux
  - osx
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
rust:
  - stable
  - beta
  - nightly
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl ; fi
script:
  - cargo build
  - RUST_BACKTRACE=1 cargo test
  - cargo test --release --no-run
  - ./target/release/examples/bench
  - cd bogo && ./runme
